# Workflow to automatically create deliverables
name: Build on push

on:
  [push, pull_request]

jobs:
  build:
    name: Assembling artifacts
    runs-on: ubuntu-latest

    steps:
      # Check out into demo/godot-xr-tools2
      - name: Checkout
        uses: actions/checkout@v6
        with:
          path: demo/godot-xr-tools2
          submodules: recursive

      # Assemble the plugin folder and clean up the demo folder
      - name: Create XR tools plugin
        run: |
          mkdir plugin
          mkdir plugin/godot-xr-tools2
          mkdir plugin/godot-xr-tools2/addons
          cp -r demo/godot-xr-tools2/addons/godot-xr-tools2 plugin/godot-xr-tools2/addons
          cp plugin/godot-xr-tools2/addons/godot-xr-tools2/CONTRIBUTORS.md demo/godot-xr-tools2

      # Remove folders we don't want to include in the releases
      - name: Cleanup
        run: |
          rm -rf demo/godot-xr-tools/.git
          rm -rf demo/godot-xr-tools/.github
          rm -rf plugin/godot-xr-tools/.git
          rm -rf plugin/godot-xr-tools/.github

      # Upload plugin
      - name: Create XR tools v2 library artifact
        uses: actions/upload-artifact@v7
        with:
          name: godot-xr-tools2
          path: |
            plugin

      # Upload demo
      - name: Create XR tools v2 demo artifact
        uses: actions/upload-artifact@v7
        with:
          name: godot-xr-tools2-demo
          path: |
            demo

      # For tagged builds create the artifact zips
      - name: Zip asset
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        run: |
          cd plugin
          zip -qq -r ../godot-xr-tools2.zip godot-xr-tools2
          cd ../demo
          zip -qq -r ../godot-xr-tools2-demo.zip godot-xr-tools2
          cd ..

          # For tagged builds create the release
      - name: Create and upload asset
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        uses: ncipollo/release-action@v1
        with:
          draft: true
          allowUpdates: true
          artifacts: "godot-xr-tools2.zip,godot-xr-tools2-demo.zip"
          omitNameDuringUpdate: true
          omitBodyDuringUpdate: true
          omitDraftDuringUpdate: true
          omitPrereleaseDuringUpdate: true
          token: ${{ secrets.GITHUB_TOKEN }}
